import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import HeaderNavigation from "@/components/header_navigation";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata: Metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} antialiased min-h-screen`}>
        <div className="fixed top-0 left-0 w-full z-50">
          <HeaderNavigation />
        </div>
        {/* TODO: how to change padding depending on discount banner visibility */}
        <div className="pt-28">{children}</div>
      </body>
    </html>
  );
}
